apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kag-eksctl-cluster
  region: us-east-1

nodeGroups:
  - name: kag-eksctl-ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: kabirg
